config/routes.rb
Lightgraphos::Application.routes.draw do
  devise_for :users
  devise_for :visitors
  resources :users
  resources :gears, only: [:new, :create, :destroy, :show]
  resources :searches
  resources :rentals, only: [ :new, :create ]

  root  'static_pages#home'
  match '/postgear', to: 'gears#new', via: 'get' #postgear_path
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/profile', to: 'static_pages#profile', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/make_money', to: 'static_pages#reason_one', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def blog
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<div id="about-area-home" class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
			</div>
			<div class="hero-unit">
				<h2>About ClyQe</h2>
				<p>
					We are three friends with different photography experiences, but we understand the need to create a home for photographers to share their gear, experiences, and knowledge. Our vision is to design ClyQe such that it’s more than just a place to rent gear but also a safe community for photographers to share technique and favorite local places.
				</p>
				<hr width="75%">
				<h2 align="center">The Team</h2>

				<div class="row">
					<div class="col-md-2">
						<h4>Mark Iglesias</h4>
					</div>
				</div>
				<div class="row add-padding-bottom">
					<div class="col-md-2">
							<%= image_tag("profile/mark.png", :size => "100x100") %>
					</div>
					<div class="col-md-10">							
						<p>
							Mark's story in Photography started when he spontaneously bought a DSLR while he was preparing for a trip. That day changed his life and wallet forever. The changes also caused him to acquire more expensive lenses and accessories. His wife was not pleased with the amount of time and money spent on this hobby, prompting him to sell most of his gear. He still misses his old gear, but is glad that he has friends like Victor and Tiffanie whom he can borrow from. He has been an avid photographer for over 10 years. Mark works in tech industry and has M.S. in Software Engineering, and M.B.A. from San Jose State University.
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col-md-2">
						<h4>Victor Sutan</h4>
					</div>
				</div>
				<div class="row add-padding-bottom">
					<div class="col-md-2">
						<%= image_tag("profile/victor.png", :size => "100x100") %>
					</div>
					<div class="col-md-10">							
						<p>
							Victor is usually out shooting, when he is not looking at binary numbers on his day job. Victor has photography experience of over 8 years. He recently completed his cross country National Park adventure in 2 months. When he is not pushing his car to the limit, he usually volunteer for a local non-profit organization as the event photographer. Victor has M.S. in Computer Engineering from Columbia University.
						</p>
					</div>
				</div>				

				<div class="row">
					<div class="col-md-2">
						<h4>Tiffanie Kong</h4>
					</div>
				</div>
				<div class="row add-padding-bottom">
					<div class="col-md-2">
						<%= image_tag("profile/tiff.png", :size => "100x100") %>
					</div>
					<div class="col-md-10">							
						<p>
							Tiffanie's passion for Photography started when she experimented with her family's first digital camera. Travelling to beautiful places inspired her to become a better photographer.  Bitten by the travel bug, she would never leave home without a camera.
							A few years later, she met Mark and Victor who helped blossom her photography skills.The three began sharing camera gear and Photography tips. Why not share their ideas and tips with others? Then, ClyQe	 was formed.
							Tiffanie lives in the heart of Silicon Valley and is working in the high tech industry. She holds a B.S. in Computer Science from UC Davis and is pursuing her MBA in Marketing. 
						</p>
					</div>
				</div>
				<p><%= link_to "Back to the homepage", home_path %></p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<h1>
				Blog
			</h1>
			<%= image_tag("CLYQE_logo_vertical_medium.png", alt: "CLYQE") %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="page-header">
			</div>
			<div class="hero-unit">
				<h3>
					We are on our way!
				</h3>
				<p>
					We are looking for early adopters to sign up and try out our service. Do you want to make extra money from your gear when you are not using them? Are you looking for gear to rent for that special assignment, project or trip? You are the perfect candidate to try out our service. Sign up and try it out!
				</p>
			</div>
		</div>

		<div class="row-fluid">
      		<div class="span12">
        		<div class="page-header">
        		</div>
        	<div class="hero-unit">
        		<h3>
        			<%= image_tag("CLYQE_logo_000.png") %> revolution has begun!
          		</h3>
          		<p>
          			Have you ever needed a lens but have been unable to afford it? Do you find it inconvenient to pack and carry your gear when traveling? Are you interested in loaning out your gear to other photographers? <%= image_tag("CLYQE_logo_000.png") %> is a community marketplace for photographers to list, discover, and share photography gear and knowledge with other photographers. We are working on making this dream come true. Sign up today and we will notify you as soon as it's ready!
          		</p>
          	</div>
		</div>
	</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="content">
  <header>
    <div class="card row">
      <div class="copy_container">
        <%if user_signed_in? %> 
          <h1><p>Welcome to ClyQe</p></h1>
          <p><%= link_to "Search for gear to rent", new_search_path, class: "btn btn-large btn-success" %></p>
          <p><%= link_to "Post gear", postgear_path, class: "btn btn-large btn-success" %></p>
          <p><%= link_to "Go to profile", current_user, class: "btn btn-default btn-success" %></p>
          <p><%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "btn btn-default btn-success" %></p>
       
        <%else %>
          <h1>A PLACE FOR YOU TO</h1>
          <h4>list gear, rent gear, and learn from each other.</h4>  
          <p>Whether you are looking for a gear on your trip or you are looking to rent out your gear, ClyQe is here to connect photographers around the world.</p> 
          <h5 class="add-padding">Currently, we are getting ready for a beta version. You can sign up below if you are interested in taking part. We'll keep you updated.</h5>

          <!--this is for getting email input and confirming email using devise-->
          <!--
          <%if flash[:suc]%>
            
            <div class="alert alert-info"><%= flash[:suc]%></div>
            
          <%elsif flash[:notice]%>
              <div class="alert alert-info">
                  <p>Please check your email to verify the account.</p></div>
          <%else%>
            <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
              <%= devise_error_messages! %>
              <%= f.text_field :email,:maxlength => 100, :placeholder => "Email Address" %>
              <%= f.submit "Sign up", class: "btn btn-success"  %>
            <%end%>
          <% end %>
          -->
          <!--this is for getting email input and confirming email using devise-->

          <!--this is for user model-->
          <p><%= link_to "Login", new_user_session_path, class: "btn btn-large btn-success" %></p>
          <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-large btn-success" %></p>
          <!--this is for user model-->


        <% end%>
      </div>
  </div>
</div>
<div id="content-area-home" class="container"> 
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>CASH</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2">  
      <h2>"Transform your unused gear into profits!"</h2>
      <p>Majority of people use their gear less than 150 days out of a year. ClyQe allows you to gain profits from unused gear. Rent out your gear when you don't need them and keep them when you do. </p>
    </div>
    <div class ="col-lg-4">
      <div class="thumbnail">
        <%= image_tag("make_money/money.png") %>
      </div>
    </div>
  </div>
</div>
<div class="color-me-gray">
  <div id="content-area-home" class="container"> 
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3>CONVENIENCE</h3>
      </div>
    </div>
    <div class="row">
      <div class ="col-md-4 col-md-offset-1">
        <div class="thumbnail">
          <%= image_tag("make_money/location.png") %>
        </div>
      </div>
      <div class="col-md-6">  
        <h2>"Rent gear wherever and whenever you need them!"</h2>
        <p>No more paying rental fee for the length of your travel. ClyQe gives you a way to rent with flexible schedule and location. Rent a gear when you need it and save money on the day that you don't. </p> 
      </div>
    </div>
  </div>
</div>
<div id="content-area-home" class="container"> 
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>COMMUNITY</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2">  
      <h2>"A place to learn with your fellow photo nerds!"</h2>
      <p>Whether you are gear owners or renters, ClyQe is a place to make friends. Learn from your fellow photographers on tips about gear, techniques, and favorite photography locations.</p> 
    </div>
    <div class ="col-md-4">
      <div class="thumbnail">
        <%= image_tag("make_money/community.png") %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/profile.html.erb
<% provide(:title, 'Profile') %>

<!--<div class="content">-->
<div class="container">
	<div class="row">	
		<article class="col-lg-offset-1 col-sm-offset-1 col-lg-8 col-sm-7 col-lg-push-3 col-sm-push-4">
	        <ul class="nav nav-tabs">
	                <li><a href="#abt" data-toggle="tab">About</a></li>
	                <li><a href="#gear" data-toggle="tab">Gears</a></li>
	                <li><a href="#trns" data-toggle="tab">Transactions</a></li>
	        </ul>
			<!-- text for each callout -->           
	    	<div class="tab-content">
	        	 <!-- Owner About -->
	            <div class="tab-pane fade active in" id="abt">
		            <p>
					Mark's story in Photography started when he spontaneously bought a DSLR while he was preparing for a trip. That day changed his life and wallet forever. The changes also caused him to acquire more lenses and more accessories. </p>
		            <p><a href="#" class="btn btn-info">Read more >></a></p>
		            <!--Reviews of Owners-->
		            	<blockquote><p>Mark is super awesome!</p></blockquote>
		        		<blockquote><p>He's ok...</p></blockquote>
	            </div> <!--close about-->

	             <!-- Owner Gears -->
	            <div class="tab-pane fade" id="gear">
	            	<div class="row">
			            <div class="col-xs-6">
	                        <div class="thumbnail alt="" img-responsive">
	                        	<%= image_tag("profile/mark.png")%>
	                           	<!--<img src="profile/mark.png" alt="" class="img-responsive">-->
	                            <p class="caption">Canon Kit.</p>
	                        </div>
	                    </div>
	                    <div class="col-xs-6">
	                        <div class="thumbnail alt="" img-responsive">  
	                            <%= image_tag("profile/mark.png")%>
	                            <p class="caption">Nikon Kit.</p> 
	                        </div>
	                    </div>
                	</div>
	            </div> <!--close owner gears-->

	             <!-- Owner Transactions -->
	             <div class="tab-pane fade" id="trns">
		             <div class="table-responsive">
	              		<table class="table table-condensed table-striped">
	                		<thead>
			                  <tr>
			                    <th>Transaction Number</th>
			                    <th>Transaction Date</th>
			                    <th>Price:</th>
			                    <th>Renter:</th>
			                  </tr>
			                </thead>
			                <tbody>
			                  <tr>
			                    <td>223445</td>
			                    <td>2014-01-29</td>
			                    <td>$35</td>
			                    <td>Chevy Chase</td>
			                  </tr>
			                  <tr>
			                    <td>998324</td>
			                    <td>2014-03-29</td>
			                    <td>$100</td>
			                    <td>Melrose Black</td>
			                  </tr>
			                  <tr>
			                    <td>3281345</td>
			                    <td>2014-04-02</td>
			                    <td>$76</td>
			                    <td>Diane Richards</td>
			                  </tr>
			                </tbody>
			            </table>
	            	</div>
		        </div>
	    	</div> <!--close tab content -->
    	</article>

        <aside class="col-lg-3 col-sm-4 col-lg-pull-9 col-sm-pull-8">
        	<div class="panel panel-default">
            	<div  class="panel-heading">
            		<span class="glyphicon glyphicon-star"></span>
                	<div class="thumbnail alt="" img-responsive"> 
          				<%= image_tag("profile/mark.png") %>
        			</div>
        			<h3>Mark</h3>
                </div>
                <div class="panel-body">
	                <p>Buddies:</p>
	                <p>Tiffanie</p>
	                <p>Victor</p>
                </div>
            </div>
         </aside>
<!--
    	<aside class="col-lg-3 col-sm-4 col-lg-pull-9 col-sm-pull-8">
        <div class="thumbnail">
          <%= image_tag("profile/mark.png") %>
        </div>
        	<h3>About Our Services</h3>
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#">Vaccinations</a></li>
                <li><a href="#">Checkups</a></li>
                <li><a href="#">Senior Pets</a></li>
                <li><a href="#">Diet Plans</a></li>
            </ul> 
         </aside>
	-->
	</div>
</div>
	<script type="http://code.jquery.com/jquery-latest.min.js"></script>
    <script type="javascripts/bootstrap.min.js"></script>
    <!--css selector-->
    <script>
        $(function () {
            $('.nav-tabs a:first').tab('show');
        });
    </script>
<!--<div class="container">-->

app/views/static_pages/reason_one.html.erb
<% provide(:title, 'Make Money') %>
<div class="main">
	<div id="how-it-works-content">
		<div class="wrapper">
			<div class="item-page">
				<div class="row row-fluid">
					<div class="span12">
						<h1>Make Money</h1>
						<p>As fellow photographers, we understand that it is very expensive to maintain a good set of gears. There is always financial justification needed with every purchase. With ClyQe, we hope to take your doubt away and provide you more than just financial incentives.</p>
						<p> </p>
					</div>
				</div>
				<div class="row infographic">
					<div class="span6">
						<%= image_tag("make_money/make_money_1.png") %>
						<p>Majority of people use their gears less than 150 days out of a year. ClyQe allows you to gain profits from unused gears. Rent out your gears when you don't need them, and keep them when you do.</p>
					</div>
					<div class="span6">
						<%= image_tag("make_money/make_money_2.png") %>
						<p>Be your own boss. You can decide the rental fees, and schedules. </p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<!--
<div class="container container-fluid container-area-home">
	<div class="row-fluid">
		<div class="span12">
			<div class="page-header">
			</div>
			<div class="hero-unit">
				<h2>Make Money</h2>
				<p>
					Photography is an expensive hobby. So, we created ClyQe for the following reasons:
				</p>
				<hr width="75%">
				<h3 align="left">1. Make your gears work for you! </h3>
				<div class="row-fluid">
					<h4>You only need to rent out your gears approximately 45 times to earn the value of your $2000 lens</h4>
					<div class="span2">
						<%= image_tag("profile/mark.png", :size => "100x100") %>
					</div>
					<div class="span8">							
						<p>
							Mark has been avid photographer for over 10 years. His interest in photography started in high school where he took a class in photgraphy and learned how to process pictures in the dark room. He started to travel more and bought a point and shoot camera. He interested in photography increased and one spontaneous day bought a DSLR. That day change his life and his wallet. He bought more lenses, change camera bodies and started buying accessories. His interested peaked when he discovered the Strobist blog and started playing with off camera flash and lighting techniques. At the same time, he discovered he accumalate too much gear and his wife was not pleased with the amount of time and money spent on this hobby. One day after a backpacking trip where the amount of camera gear he brought on that trip almost broke his back, he decided that that he needed to downsize his equipment that he cherished and adored. He sold all his DSLR gear and is now using Micro 4/3 equipment. He still misses all his old gear but is glad he has friend he can borrow from.
						</p>
					</div>
				</div>
				<div class="row-fluid">
					<h4>Tiffanie Kong</h4>
					<div class="span2">
						<%= image_tag("profile/tiff.png", :size => "100x100") %>
					</div>
					<div class="span8">							
						<p>
							Tiff is an alcoholic...
						</p>
					</div>
				</div>
				<div class="row-fluid">
					<h3>Victor Sutan</h3>
					<div class="span2">
						<%= image_tag("profile/victor.png", :size => "100x100") %>
					</div>
					<div class="span8">							
						<p>
							Victor is usually out shooting, when he is not looking at binary numbers on his day job. Victor has photography experience of 8 years. He recently completed his cross country National Park adventure in 2 months. Victor has M.S. in Computer Engineering from Columbia University.
						</p>
					</div>
				</div>
				<p><%= link_to "Back to the homepage"%></p>
			</div>

		</div>
	</div>
</div>-->