config/routes.rb
Lightgraphos::Application.routes.draw do
  devise_for :users
  devise_for :visitors
  resources :users
  resources :gears, only: [:new, :create, :destroy, :show]
  resources :searches
  resources :rentals, only: [ :new, :create ]

  root  'static_pages#home'
  match '/postgear', to: 'gears#new', via: 'get' #postgear_path
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/profile', to: 'static_pages#profile', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/make_money', to: 'static_pages#reason_one', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'

  

end

app/models/gear.rb
class Gear < ActiveRecord::Base
	belongs_to :user
	# validates is used on the new gears form to show errors messages if fields are not populdated correctly
	validates :user_id, presence: true
	validates :title, presence: true
	validates :brand, presence: true
	validates :component, presence: true
	validates :daily_rental_price, presence: true
	validates :daily_rental_price, :numericality =>{:greater_than => 0}
	validates :description, presence: true

	def self.search(search)
		if search
		find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
		#else
			#find(:all)
		end
	end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
	#before_action :signed_in_user
  before_action :correct_user,   only: :destroy

  def new
  	@gear = current_user.gears.build()
  end

  def destroy
    @gear.destroy
    redirect_to current_user
  end

  def create
  	@gear = current_user.gears.build(gear_params)
  	if @gear.save
  		#handle a successful post of gear
  		flash[:success] = "Gear posted!"
  		redirect_to current_user #redirects to current users profile page
  	else
      @posts_items = []
  		render 'new' #renders the post gear page but should display error messages if any
  	end
  end

  def show
    @gear = current_user.gears.find(params[:id]) #add code
  end

  def searchgear
    @gears = Gear.search(params[:search])
  end

  private

  	# this code enables requirements of paraments in the post gear form
  	def gear_params
  		params.require(:gear).permit(:title, :brand, :component, :daily_rental_price, :description)
  	end

    def correct_user
      @gear = current_user.gears.find_by(id: params[:id])
      redirect_to current_user if @gear.nil?
    end

end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/gears/_gear.html.erb
<li>
  <span class="title"><%= gear.title %></span>
  <% if current_user?(gear.user) %>
    <%= link_to "delete", gear, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: gear.title %>
  <% end %>
</li>

app/views/gears/new.html.erb
<% provide(:title, "Post Gear") %>
<div class="container fluid">
<div id="pg-content" class="content" >
    <div class="row">
    <h1>Post Gear</h1>
      <div class="span6 offset3">
        <%= form_for(@gear, :html => {:multipart => true}) do |f| %>

          <%= render 'shared/error_messages', object: f.object %>
          <div><%= f.label :title %><br />
          <%= f.text_field :title %></div>

          <div><%= f.label :brand %><br />
          <%= f.select :brand, [ "Canon", "Nikon", "Sigma", "Panasonic", "Leica", "Olympus", "Fujifilm", "Mamiya", "Minolta", "Bower", "GoPro", "Sanyo", "Ricoh", "Pentax", " Lytro" ], :prompt => 'Select Brand'%></div>

          <div><%= f.label :component %><br />
          <%= f.select :component, [ "Body", "Lens", "Accessory" ], :prompt => 'Select Component' %></div>

          <div><%= f.label :daily_rental_price %><br />
          <%= f.text_field :daily_rental_price %></div>

          <div><%= f.label :description %><br />
          <%= f.text_field :description %></div>

          <!--add photo of gear -->
          <div><%= f.label :gear_picture %><br />
          <%= f.file_field :gear_picture, :style => "width:400px;"  %></div> 
          
          <%= f.submit "Post gear now!", class: "btn btn-default btn-success" %>
        <% end %>

      </div>
    </div>
  </div>
</div>
</div>

app/views/gears/searchgear.html.erb
<% provide(:title, "Search Gear") %>
<h1>Search Gear</h1>

<!--
<form class="form-search">
	<input type="text" class="span3 search-query" placeholder="Search gear"/>
	<button class="btn">Search</button>
</form>
-->

<%= form_tag gears_path, :method => 'get' do %>
	<p>
		<!--1st parameter is the parameter name, the 2nd param params[:search] is the value shown on the page after clicking submit-->
		<%= text_field_tag :search, params[:search] %>
		<!--:name => nil  means name of the submit_tag will not show up on the url -->
		<%= submit_tag "Search", :name => nil %>
	</p>
<% end %>

<% if not @gears.blank?  %>
	<% @gears.each do |gear| %>
	  <p><%= gear.title %></p>

	<% end %>
<% end %>

app/views/gears/show.html.erb
<% provide(:title, "Gear Info") %>
<h1>Gear info for <%= @gear.title %></h1>

<div class="row">
  <div class="span3">
  	<h5>Brand</h5>
  	<p><%= @gear.brand %></p>
  </div>

  <div class="span3">
  	<h5>Component</h5>
  	<p><%= @gear.component %></p>
  </div>

  <div class="span3">
  	<h5>Daily Rental Price</h5>
  	<p><%= @gear.daily_rental_price %></p>
  </div>

  <div class="span3">
  	<h5>Description</h5>
  	<p><%= @gear.description %></p>
  </div>
</div>

<%= link_to "Go to profile", current_user, class: "btn btn-default btn-success" %>