config/routes.rb
Lightgraphos::Application.routes.draw do
  devise_for :users
  devise_for :visitors
  resources :users
  resources :gears, only: [:new, :create, :destroy, :show]
  resources :searches
  resources :rentals, only: [ :new, :create ]

  root  'static_pages#home'
  match '/postgear', to: 'gears#new', via: 'get' #postgear_path
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/profile', to: 'static_pages#profile', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/make_money', to: 'static_pages#reason_one', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'

  

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

	def create
		@subscriber = Subscriber.new(subscriber_params)
		@subscriber.save
		flash[:success] = "Welcome to CLYQE!"
		redirect_to home_path
	end

	def new
		@subscriber = Subscriber.new
	end

	private

	    def subscriber_params
    		params.require(:subscriber).permit(:email)
    	end


end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/new.html.erb
<% provide(:title, 'Subscribe') %>
<h1>Subscribe</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@subscriber) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :email1 %>
      <%= f.text_field :email %>
      <%= f.submit "Create my account", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@subscriber) do |f| %>
      <%= f.label :email1 %>
      <%= f.text_field :email %>
      <%= f.submit "Create my account", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="span6 offset3">

    <div class="input-group">
      <input type="text" class="form-control subscribe-bar" placeholder="Email Address 3">
      <span class="input-group-btn">
        <!--<button class="btn btn-default" type="button">Sign Up!</button>-->
        <%= link_to "Sign up now!", signup_path, class: "btn btn-success" %>
      </span>
    </div> 

  </div>
</div>

<div class="row">
  <div class="span6 offset3">
    <% form_tag(signup_path, :method => "get") do %>
    <% label_tag(:q, "Search for:") %>
    <% text_field_tag(:q) %>
    <% submit_tag("Search") %>
    <% end %>
  </div>
</div>